export const GAME_CONSTANTS = {
    ROUNDS_COUNT: 3,
    MIN_TEAMS: 2,
    MAX_TEAMS: 5,
    MIN_PLAYERS_PER_TEAM: 2,
    MAX_PLAYERS_PER_TEAM: 3,
    MIN_WORDS_PER_PLAYER: 1,
    MAX_WORDS_PER_PLAYER: 5,
    TURN_TIME_DEFAULT: 60,
    WORDS_PER_PLAYER_DEFAULT: 4
}